version: "3.8"

services:
  nginx:
    build:
      context: ./Nginx
    depends_on:
      - client
      - mysql
    networks:
      - backend
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  client:
    build:
      context: ./Client
    networks:
      - backend
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_USER=bes
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows
      - MYSQL_PORT=3306
    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  mysql:
    image: mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_USER=bes
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows
      - MYSQL_PORT=3306
    volumes:
      - ~/docker/Snowboards/mysql:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

  # ==============================================================================================================================

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    user: root
    environment:
      - TEST=bal
    volumes:
      - ~/docker/Snowboards/grafana:/var/lib/grafana
    # ==============================================================================================================================

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
