version: "3.8"

services:
  nginx:
    build:
      context: ./Nginx
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  php-fpm:
    build:
      context: ./Client
      args:
        user: bes
        uid: 1000
    depends_on:
      - mysql
      - redis
    networks:
      - backend
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows_bes
      - MYSQL_PORT=3307

    env_file:
      - .env

    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  mysql:
    image: mysql
    networks:
      - backend
    ports:
      - "3307:3307"
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows_bes
      - MYSQL_PORT=3307
      - MYSQL_TCP_PORT=3307
      - MYSQL_UNIX_PORT=3307
    volumes:
      - ~/docker/Snowboards/mysql:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

  # ==============================================================================================================================

  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - "6369:6379"
    command: redis-server

    # ==============================================================================================================================

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3500:3000"
    networks:
      - frontend
    user: root
    volumes:
      - ~/docker/Snowboards/grafana:/var/lib/grafana
    # ==============================================================================================================================

networks:
  frontend:
  backend:
