version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - /home/bes/docker/Snowboards/jenkins:/var/jenkins_home
    ports:
      - "9100:8080"
    build:
      context: ./jenkins

  grafana:
    image: grafana/grafana
    environment:
      - TEST=bal
    volumes:
      - /home/bes/docker/Snowboards/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    user: root
