version: "3.8"

services:
  nginx:
    build:
      context: ./Nginx
    depends_on:
      - php-fpm
      - mysql
    networks:
      - backend
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  php-fpm:
    build:
      context: ./Php-Fpm
    depends_on:
      - mysql
      - redis
    networks:
      - backend
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows_bes
      - MYSQL_PORT=3307

    volumes:
      - ./Client:/var/www/html:delegated

  # ==============================================================================================================================

  mysql:
    image: mysql
    networks:
      - backend
    ports:
      - "3307:3307"
    environment:
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows_bes
      - MYSQL_PORT=3307
      - MYSQL_TCP_PORT=3307
      - MYSQL_UNIX_PORT=3307
    volumes:
      - ~/docker/Snowboards/mysql:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

  # ==============================================================================================================================

  redis:
    image: redis:latest
    ports:
      - "6369:6379"
    networks:
      - backend
    command: redis-server

    # ==============================================================================================================================

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "4000:3000"
    user: root
    environment:
      - TEST=bal
    volumes:
      - ~/docker/Snowboards/grafana:/var/lib/grafana
    # ==============================================================================================================================

networks:
  frontend:
  backend:
