version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - ~/docker/Snowboards/Jenkins:/var/jenkins_home
      - ~/docker/Snowboards/Jenkins:/var/jenkins_config
    ports:
      - "9100:8080"
    build:
      context: ./Jenkins

  mysql:
    image: mysql
    environment:
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_USER=bes
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=snows
      - MYSQL_PORT=3307
    volumes:
      - ~/docker/Snowboards/Mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  grafana:
    image: grafana/grafana
    environment:
      - TEST=bal
    volumes:
      - ~/docker/Snowboards/grafana:/var/lib/grafana
    ports:
      - "4000:3000"
    user: root
